# Generated by Django 2.2.1 on 2019-06-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='ffsd', max_length=200),
            preserve_default=False,
        ),
    ]
